version: 2.1

commands:
  checkout_with_workspace:
    steps:
      - checkout
      - attach_workspace:
          at: ~/

jobs:
  test-php:
    docker:
      - image: circleci/php:7.4
      - image: circleci/mysql:5.6
    environment:
      - WP_TESTS_DIR: '/tmp/wordpress-tests-lib'
      - WP_CORE_DIR: '/tmp/wordpress/'
    steps:
      - checkout_with_workspace
      - run:
          name: Setup Environment Variables
          command: |
            echo "export PATH=$HOME/.composer/vendor/bin:$PATH" >> $BASH_ENV
            source /home/circleci/.bashrc
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update && sudo apt-get install subversion
            sudo -E docker-php-ext-install mysqli
            sudo apt-get update && sudo apt-get install default-mysql-client
      - run:
          name: Run Tests
          command: |
            composer install
            rm -rf $WP_TESTS_DIR $WP_CORE_DIR
            bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 latest
            ./vendor/bin/phpunit

  release_github:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout_with_workspace
      - run:
          name: Install npm dependencies
          command: npm ci
      - run:
          name: Install rsync
          command: sudo apt install rsync
      - run:
          name: Release new version on Github
          command: npm run release
      # Persist assets generated for the GH release, so that they are available for WPORG release.
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  release_wporg:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout_with_workspace
      - run:
          name: Release new version on WordPress.org
          command: ./node_modules/newspack-scripts/release-wporg.sh

  post_release:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout_with_workspace
      - run:
          name: Perform post-release chores
          command: ./node_modules/newspack-scripts/post-release.sh

workflows:
  version: 2
  main:
    jobs:
      - test-php
      - release_github:
          filters:
            branches:
              only:
                - release
                - alpha
                - /^hotfix\/.*/
                - /^epic\/.*/
      - post_release:
          requires:
            - release_github
          filters:
            branches:
              only:
                - release
      - release_wporg:
          requires:
            - release_github
          filters:
            branches:
              only:
                - release
