version: 2.1

jobs:
  test-php:
    docker:
      - image: circleci/php:7.2
      - image: circleci/mysql:5.6
    environment:
      - WP_TESTS_DIR: "/tmp/wordpress-tests-lib"
      - WP_CORE_DIR: "/tmp/wordpress/"
    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            echo "export PATH=$HOME/.composer/vendor/bin:$PATH" >> $BASH_ENV
            source /home/circleci/.bashrc
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update && sudo apt-get install subversion
            sudo -E docker-php-ext-install mysqli
            sudo apt-get update && sudo apt-get install default-mysql-client
      - run:
          name: Run Tests
          command: |
            composer global require "phpunit/phpunit=5.7.*"
            rm -rf $WP_TESTS_DIR $WP_CORE_DIR
            bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 latest
            phpunit

workflows:
  version: 2
  all:
    jobs:
      - test-php
